# Generated by Django 5.2.1 on 2025-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='N/A', max_length=100)),
                ('college_location', models.CharField(default='N/A', max_length=100)),
                ('college_affiliation', models.CharField(default='N/A', max_length=100)),
                ('college_logo', models.ImageField(default='college_logos/default.png', upload_to='college_logos/')),
                ('college_website', models.URLField(default='https://www.example.com')),
                ('college_mobile_no', models.CharField(default='N/A', max_length=15)),
                ('college_email', models.EmailField(default='N/A', max_length=100)),
                ('college_description', models.TextField(default='N/A')),
            ],
            options={
                'db_table': 'college',
            },
        ),
    ]
