# Generated by Django 5.2.1 on 2025-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='N/A', max_length=100)),
                ('student_reg_no', models.CharField(default='N/A', max_length=20)),
                ('student_branch', models.CharField(default='N/A', max_length=50)),
                ('student_year', models.CharField(default='N/A', max_length=20)),
                ('student_skills', models.CharField(default='N/A', max_length=20)),
                ('student_image', models.ImageField(default='college_logos/default.png', upload_to='college_logos/')),
                ('student_mobile_no', models.CharField(default='N/A', max_length=15)),
                ('student_email', models.EmailField(default='N/A', max_length=100)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
