# Generated by Django 5.2.1 on 2025-06-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_affiliation',
            new_name='college_University',
        ),
    ]
