# Generated by Django 5.2.1 on 2025-06-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_college_affiliation_college_college_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_University',
            new_name='college_university',
        ),
    ]
