# Generated by Django 5.2.1 on 2025-06-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_college_university_college_college_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
