# Generated by Django 5.2.1 on 2025-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_college_admin_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rating (1-5 stars)'),
        ),
    ]
