# Generated by Django 5.2.1 on 2025-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_college_college_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='student_images/default.png', upload_to='student_images/'),
        ),
    ]
