# Generated by Django 5.2.1 on 2025-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_student_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_registration_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='college_registration_password',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
