# Generated by Django 5.2.1 on 2025-06-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_college_college_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_registration_password',
            field=models.CharField(default='N/A', max_length=128),
        ),
    ]
