# Generated by Django 5.2.1 on 2025-06-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_college_college_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='N/A', max_length=100)),
                ('company_location', models.CharField(default='N/A', max_length=100)),
                ('company_logo', models.ImageField(default='company_logos/default.png', upload_to='company_logos/')),
                ('company_website', models.URLField(default='https://www.example.com')),
                ('company_mobile_no', models.CharField(default='N/A', max_length=15)),
                ('company_email', models.EmailField(default='N/A', max_length=100)),
                ('company_description', models.TextField(default='N/A')),
                ('company_registration_id', models.CharField(default='N/A', max_length=20)),
                ('company_registration_password', models.CharField(default='N/A', max_length=128)),
                ('admin_verified', models.BooleanField(default=False)),
                ('company_rating', models.PositiveSmallIntegerField(default=0, help_text='Rating (1-5 stars)')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
